-- ============================================================
-- dim_date.sql — Dimension calendrier (Shared Seeds)
-- ============================================================
-- Grain : 1 ligne = 1 jour calendaire
-- Source : data/synthetic/team_*/shared/dim_date.csv
-- Colonnes :
--   date_key      DATE  (PK, ISO format YYYY-MM-DD)
--   year          INT
--   quarter       INT   (1-4)
--   month         INT   (1-12)
--   month_name    VARCHAR (January, February, …)
--   week_iso      INT   (1-53)
--   day_of_week   INT   (1=Monday … 7=Sunday)
--   day_name      VARCHAR (Monday, Tuesday, …)
--   is_weekend    INT   (0 ou 1)
-- SCD : Aucun — dimension statique (calendrier fixe)
-- ============================================================

-- TODO (S02) : Écrire le CREATE TABLE
--   - PK sur date_key
--   - Envisager des colonnes dérivées : fiscal_year, is_holiday

-- TODO (S02) : Écrire INSERT/SELECT depuis raw_dim_date
